#' Construct an OKX API request object
#'
#' Builds a structured HTTP request including the full URL and signed headers,
#' ready to be passed to a downstream execution function.
#'
#' @param httr_method HTTP method as a string, such as \code{"GET"} or \code{"POST"}.
#' @param base_url The base URL of the OKX API, typically \code{"https://www.okx.com"}.
#' @param api_path The endpoint path, e.g., \code{"/api/v5/account/balance"}.
#' @param query_string A string starting with \code{"?"} for GET parameters, or \code{""} for none.
#' @param config A named list containing credentials: \code{api_key}, \code{secret_key}, and \code{passphrase}.
#' @param body_json JSON string for the request body (used in POST methods).
#'
#' @return A named list containing:
#' \describe{
#'   \item{method}{The HTTP method (e.g., \code{"GET"} or \code{"POST"}).}
#'   \item{url}{The full request URL including query string.}
#'   \item{full_path}{Concatenated endpoint path and query string.}
#'   \item{headers}{Signed request headers generated by \code{.get_headers()}.}
#'   \item{body_json}{The request body as JSON (for POST).}
#' }
#'
#' @keywords internal
.build_request <- function(httr_method, base_url, api_path, query_string, config, body_json = "") {
  full_path <- paste0(api_path, query_string)
  full_url  <- paste0(base_url, full_path)
  headers   <- .get_headers(config, httr_method, full_path, body_json)

  list(
    method     = httr_method,
    url        = full_url,
    full_path  = full_path,
    headers    = headers,
    body_json  = body_json
  )
}
